// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MFVec2f.proto

package protobuf;

public final class MFVec2fProtos {
  private MFVec2fProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MFVec2fOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated float x = 1 [packed = true];
    java.util.List<java.lang.Float> getXList();
    int getXCount();
    float getX(int index);
    
    // repeated float y = 2 [packed = true];
    java.util.List<java.lang.Float> getYList();
    int getYCount();
    float getY(int index);
  }
  public static final class MFVec2f extends
      com.google.protobuf.GeneratedMessage
      implements MFVec2fOrBuilder {
    // Use MFVec2f.newBuilder() to construct.
    private MFVec2f(Builder builder) {
      super(builder);
    }
    private MFVec2f(boolean noInit) {}
    
    private static final MFVec2f defaultInstance;
    public static MFVec2f getDefaultInstance() {
      return defaultInstance;
    }
    
    public MFVec2f getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.MFVec2fProtos.internal_static_protobuf_MFVec2f_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.MFVec2fProtos.internal_static_protobuf_MFVec2f_fieldAccessorTable;
    }
    
    // repeated float x = 1 [packed = true];
    public static final int X_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Float> x_;
    public java.util.List<java.lang.Float>
        getXList() {
      return x_;
    }
    public int getXCount() {
      return x_.size();
    }
    public float getX(int index) {
      return x_.get(index);
    }
    private int xMemoizedSerializedSize = -1;
    
    // repeated float y = 2 [packed = true];
    public static final int Y_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> y_;
    public java.util.List<java.lang.Float>
        getYList() {
      return y_;
    }
    public int getYCount() {
      return y_.size();
    }
    public float getY(int index) {
      return y_.get(index);
    }
    private int yMemoizedSerializedSize = -1;
    
    private void initFields() {
      x_ = java.util.Collections.emptyList();;
      y_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getXList().size() > 0) {
        output.writeRawVarint32(10);
        output.writeRawVarint32(xMemoizedSerializedSize);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeFloatNoTag(x_.get(i));
      }
      if (getYList().size() > 0) {
        output.writeRawVarint32(18);
        output.writeRawVarint32(yMemoizedSerializedSize);
      }
      for (int i = 0; i < y_.size(); i++) {
        output.writeFloatNoTag(y_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getXList().size();
        size += dataSize;
        if (!getXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getYList().size();
        size += dataSize;
        if (!getYList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        yMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.MFVec2fProtos.MFVec2f parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.MFVec2fProtos.MFVec2f prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.MFVec2fProtos.MFVec2fOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.MFVec2fProtos.internal_static_protobuf_MFVec2f_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.MFVec2fProtos.internal_static_protobuf_MFVec2f_fieldAccessorTable;
      }
      
      // Construct using protobuf.MFVec2fProtos.MFVec2f.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.MFVec2fProtos.MFVec2f.getDescriptor();
      }
      
      public protobuf.MFVec2fProtos.MFVec2f getDefaultInstanceForType() {
        return protobuf.MFVec2fProtos.MFVec2f.getDefaultInstance();
      }
      
      public protobuf.MFVec2fProtos.MFVec2f build() {
        protobuf.MFVec2fProtos.MFVec2f result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.MFVec2fProtos.MFVec2f buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.MFVec2fProtos.MFVec2f result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.MFVec2fProtos.MFVec2f buildPartial() {
        protobuf.MFVec2fProtos.MFVec2f result = new protobuf.MFVec2fProtos.MFVec2f(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = java.util.Collections.unmodifiableList(x_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.x_ = x_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = java.util.Collections.unmodifiableList(y_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.y_ = y_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.MFVec2fProtos.MFVec2f) {
          return mergeFrom((protobuf.MFVec2fProtos.MFVec2f)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.MFVec2fProtos.MFVec2f other) {
        if (other == protobuf.MFVec2fProtos.MFVec2f.getDefaultInstance()) return this;
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        if (!other.y_.isEmpty()) {
          if (y_.isEmpty()) {
            y_ = other.y_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureYIsMutable();
            y_.addAll(other.y_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              ensureXIsMutable();
              x_.add(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addX(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              ensureYIsMutable();
              y_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addY(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated float x = 1 [packed = true];
      private java.util.List<java.lang.Float> x_ = java.util.Collections.emptyList();;
      private void ensureXIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          x_ = new java.util.ArrayList<java.lang.Float>(x_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Float>
          getXList() {
        return java.util.Collections.unmodifiableList(x_);
      }
      public int getXCount() {
        return x_.size();
      }
      public float getX(int index) {
        return x_.get(index);
      }
      public Builder setX(
          int index, float value) {
        ensureXIsMutable();
        x_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addX(float value) {
        ensureXIsMutable();
        x_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureXIsMutable();
        super.addAll(values, x_);
        onChanged();
        return this;
      }
      public Builder clearX() {
        x_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // repeated float y = 2 [packed = true];
      private java.util.List<java.lang.Float> y_ = java.util.Collections.emptyList();;
      private void ensureYIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          y_ = new java.util.ArrayList<java.lang.Float>(y_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Float>
          getYList() {
        return java.util.Collections.unmodifiableList(y_);
      }
      public int getYCount() {
        return y_.size();
      }
      public float getY(int index) {
        return y_.get(index);
      }
      public Builder setY(
          int index, float value) {
        ensureYIsMutable();
        y_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addY(float value) {
        ensureYIsMutable();
        y_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllY(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureYIsMutable();
        super.addAll(values, y_);
        onChanged();
        return this;
      }
      public Builder clearY() {
        y_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.MFVec2f)
    }
    
    static {
      defaultInstance = new MFVec2f(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.MFVec2f)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MFVec2f_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_MFVec2f_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMFVec2f.proto\022\010protobuf\"\'\n\007MFVec2f\022\r\n\001" +
      "x\030\001 \003(\002B\002\020\001\022\r\n\001y\030\002 \003(\002B\002\020\001B\031\n\010protobufB\r" +
      "MFVec2fProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_MFVec2f_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_MFVec2f_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_MFVec2f_descriptor,
              new java.lang.String[] { "X", "Y", },
              protobuf.MFVec2fProtos.MFVec2f.class,
              protobuf.MFVec2fProtos.MFVec2f.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
