// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rotation.proto

package protobuf;

public final class RotationProtos {
  private RotationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RotationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional float q1 = 1;
    boolean hasQ1();
    float getQ1();
    
    // optional float q2 = 2;
    boolean hasQ2();
    float getQ2();
    
    // optional float q3 = 3;
    boolean hasQ3();
    float getQ3();
    
    // optional float q4 = 4;
    boolean hasQ4();
    float getQ4();
  }
  public static final class Rotation extends
      com.google.protobuf.GeneratedMessage
      implements RotationOrBuilder {
    // Use Rotation.newBuilder() to construct.
    private Rotation(Builder builder) {
      super(builder);
    }
    private Rotation(boolean noInit) {}
    
    private static final Rotation defaultInstance;
    public static Rotation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Rotation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.RotationProtos.internal_static_protobuf_Rotation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.RotationProtos.internal_static_protobuf_Rotation_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional float q1 = 1;
    public static final int Q1_FIELD_NUMBER = 1;
    private float q1_;
    public boolean hasQ1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public float getQ1() {
      return q1_;
    }
    
    // optional float q2 = 2;
    public static final int Q2_FIELD_NUMBER = 2;
    private float q2_;
    public boolean hasQ2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getQ2() {
      return q2_;
    }
    
    // optional float q3 = 3;
    public static final int Q3_FIELD_NUMBER = 3;
    private float q3_;
    public boolean hasQ3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getQ3() {
      return q3_;
    }
    
    // optional float q4 = 4;
    public static final int Q4_FIELD_NUMBER = 4;
    private float q4_;
    public boolean hasQ4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getQ4() {
      return q4_;
    }
    
    private void initFields() {
      q1_ = 0F;
      q2_ = 0F;
      q3_ = 0F;
      q4_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, q1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, q2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, q3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, q4_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, q1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, q2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, q3_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, q4_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.RotationProtos.Rotation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.RotationProtos.Rotation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.RotationProtos.Rotation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.RotationProtos.Rotation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.RotationProtos.Rotation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.RotationProtos.RotationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.RotationProtos.internal_static_protobuf_Rotation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.RotationProtos.internal_static_protobuf_Rotation_fieldAccessorTable;
      }
      
      // Construct using protobuf.RotationProtos.Rotation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        q1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        q2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        q3_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        q4_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.RotationProtos.Rotation.getDescriptor();
      }
      
      public protobuf.RotationProtos.Rotation getDefaultInstanceForType() {
        return protobuf.RotationProtos.Rotation.getDefaultInstance();
      }
      
      public protobuf.RotationProtos.Rotation build() {
        protobuf.RotationProtos.Rotation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.RotationProtos.Rotation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.RotationProtos.Rotation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.RotationProtos.Rotation buildPartial() {
        protobuf.RotationProtos.Rotation result = new protobuf.RotationProtos.Rotation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.q1_ = q1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.q2_ = q2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.q3_ = q3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.q4_ = q4_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.RotationProtos.Rotation) {
          return mergeFrom((protobuf.RotationProtos.Rotation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.RotationProtos.Rotation other) {
        if (other == protobuf.RotationProtos.Rotation.getDefaultInstance()) return this;
        if (other.hasQ1()) {
          setQ1(other.getQ1());
        }
        if (other.hasQ2()) {
          setQ2(other.getQ2());
        }
        if (other.hasQ3()) {
          setQ3(other.getQ3());
        }
        if (other.hasQ4()) {
          setQ4(other.getQ4());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              q1_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              q2_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              q3_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              q4_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional float q1 = 1;
      private float q1_ ;
      public boolean hasQ1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public float getQ1() {
        return q1_;
      }
      public Builder setQ1(float value) {
        bitField0_ |= 0x00000001;
        q1_ = value;
        onChanged();
        return this;
      }
      public Builder clearQ1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        q1_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float q2 = 2;
      private float q2_ ;
      public boolean hasQ2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getQ2() {
        return q2_;
      }
      public Builder setQ2(float value) {
        bitField0_ |= 0x00000002;
        q2_ = value;
        onChanged();
        return this;
      }
      public Builder clearQ2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        q2_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float q3 = 3;
      private float q3_ ;
      public boolean hasQ3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getQ3() {
        return q3_;
      }
      public Builder setQ3(float value) {
        bitField0_ |= 0x00000004;
        q3_ = value;
        onChanged();
        return this;
      }
      public Builder clearQ3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        q3_ = 0F;
        onChanged();
        return this;
      }
      
      // optional float q4 = 4;
      private float q4_ ;
      public boolean hasQ4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public float getQ4() {
        return q4_;
      }
      public Builder setQ4(float value) {
        bitField0_ |= 0x00000008;
        q4_ = value;
        onChanged();
        return this;
      }
      public Builder clearQ4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        q4_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Rotation)
    }
    
    static {
      defaultInstance = new Rotation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Rotation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Rotation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Rotation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Rotation.proto\022\010protobuf\":\n\010Rotation\022\n" +
      "\n\002q1\030\001 \001(\002\022\n\n\002q2\030\002 \001(\002\022\n\n\002q3\030\003 \001(\002\022\n\n\002q4" +
      "\030\004 \001(\002B\032\n\010protobufB\016RotationProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Rotation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Rotation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Rotation_descriptor,
              new java.lang.String[] { "Q1", "Q2", "Q3", "Q4", },
              protobuf.RotationProtos.Rotation.class,
              protobuf.RotationProtos.Rotation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
